sudo: false

language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_script:
  - composer selfupdate
  - composer install --no-progress --profile --prefer-dist --no-interaction

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v
